version: '3.8'

services:
  
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  clickhouse:
    # latest LTS version of ClickHouse since 2024.
    image: clickhouse:lts-focal

    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clikchouse/init-clickhouse.sh:/docker-entrypoint-initdb.d/init-clickhouse.sh

    # inist script for CH schemas
    entrypoint: /docker-entrypoint-initdb.d/init-clickhouse.sh

    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""

  # grafana with init script to load clikchouse official plugin  
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/init-grafana.sh:/init-grafana.sh
      - grafana_data:/var/lib/grafana
    entrypoint: /init-grafana.sh
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    

volumes:
  clickhouse_data:
  grafana_data: