apiVersion: 1

datasources:
  - name: ClickHouse
    #type: vertamedia-clickhouse-datasource
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    jsonData:
      defaultDatabase: default
      #usePOST: false
      port: 8123
      host: clickhouse
      protocol: http